apiVersion: template.openshift.io/v1
kind: Template 
metadata:
  name: nodejs-ci-pipeline-template
  namespace: openshift
  annotations:
    description: Template para aprovisionar recursos para pipelines
parameters:
  - name: APP_NAME
    required: true
  - name: GIT_REPO
    required: true
  - name: BASE_PROJECT
    required: true
objects:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: ${APP_NAME}-nodejs-ci-pipeline
  spec:
    params:
    - default: ${APP_NAME}
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: ${GIT_REPO}
      description: The application git repository url
      name: SOURCE_GIT_URL
      type: string
    - default: develop
      description: The application git repository revision
      name: SOURCE_GIT_REVISION
      type: string
    - default: ${APP_NAME}
      description: The subdirectory in the git repository
      name: SOURCE_GIT_CONTEXT_DIR
      type: string
    - default: dev-${BASE_PROJECT}
      description: Namespace where the buildconfig is located
      name: NAMESPACE
      type: string
    tasks:
      - name: git-clone
        retries: 2
        params:
          - name: url
            value: $(params.SOURCE_GIT_URL)
          - name: revision
            value: $(params.SOURCE_GIT_REVISION)
          - name: subdirectory
            value: $(params.SOURCE_GIT_CONTEXT_DIR)
          - name: deleteExisting
            value: 'true'
        taskRef:
          kind: ClusterTask
          name: git-clone
        workspaces:
          - name: output
            workspace: app-source
      - name: nodejs-build
        retries: 3
        params:
          - name: PATH_CONTEXT
            value: $(params.SOURCE_GIT_CONTEXT_DIR)
        runAfter:
          - git-clone
        taskRef:
          kind: ClusterTask
          name: nodejs-build-custom
        workspaces:
          - name: source
            workspace: app-source
      - name: build-image
        retries: 3
        params:
          - name: FROM_DIRECTORY
            value: ./source/$(params.SOURCE_GIT_CONTEXT_DIR)/dist
          - name: NAMESPACE
            value: $(params.NAMESPACE)
          - name: BUILDCONFIG
            value: $(params.APP_NAME)
        runAfter:
          - nodejs-build
        taskRef:
          kind: ClusterTask
          name: s2i-binary-custom
        workspaces:
          - name: source
            workspace: app-source
    workspaces:
      - name: app-source
