apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: manifest-cd-trigger-template
  namespace: cicd
spec:
  params:
    - description: The git repository url
      name: git-repo-url
    - default: master
      description: The git revision
      name: git-revision
    - description: The name of the deployment to be created / patched
      name: app-name
    - description: The prefix of namespace
      name: base-project
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.app-name)-manifest-cd-pipeline-
        namespace: uat-$(tt.params.base-project)
      spec:
        params:
          - name: APP_NAME
            value: $(tt.params.app-name)
          - name: GIT_KUSTOMIZE
            value: $(tt.params.git-repo-url)
          - name: KUSTOMIZE_GIT_REVISION
            value: $(tt.params.git-revision)
          - name: BASE_PROJECT
            value: $(tt.params.base-project)
        pipelineRef:
          name: $(tt.params.app-name)-manifest-cd-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: app-source
            persistentVolumeClaim:
              claimName: workspace-pvc
